// playgrounds/react/src/app.tsx
import type { FC } from 'react'
import DeepFile from './xxx/yyy/zzzzzzzzzzz'

const index: FC = () => {
  const a = 1
  const b = 2
  console.log(a, b)
  return (
    <div>
      <button onClick={() => {
        debugger
        console.log(a, b)
      }}>点击log a和b</button>
      <br/>
      <br/>
      <br/>
      <br/>
      <DeepFile />
    </div>
  )
}

export default index

// playgrounds/vue/src/App.vue
<script lang="ts" setup>
const a = 1
console.log(a)

function onClick() {
  const b = true
  const c = null
  const d = {
    a: 1,
    b: 2,
    d: false,
  }
  console.log(a, b, c, d)
}
</script>

<template>
  <div>
    <button @click="onClick">
      click to log
    </button>
  </div>
</template>
